### ISSUE TITLE
Scala clean install fails

### ISSUE THREAD

**Issue by ittaiz** [takari/polyglot-maven-examples#1]
Hi,
I've cloned the repo and ran `mvn clean install` and I'm getting

```
[ERROR] Error executing Maven.
[ERROR] Compiler exception error: : error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(class java.lang.RuntimeException/bad constant pool tag 18 at byte 10)
error: : error while loading ExecuteContext, class file '/Users/ittaiz/.m2/repository/io/takari/polyglot/polyglot-common/0.1.5/polyglot-common-0.1.5.jar(org/sonatype/maven/polyglot/execute/ExecuteContext.class)' is broken
(class java.lang.NullPointerException/)
```

Could this be a problem with jdk8? I'm running with 8u40 on mac os x

**Comment by jvanzyl** [comment]
I put in the example that @huntc provided for me. I have not personally tried with Java8 so there might be some issues. Maybe Chris can help you out.

**Comment by jvanzyl** [comment]
@ittaiz Does it work with Java7?

**Comment by ittaiz** [comment]
just tried it and no.
in this [gist](https://gist.github.com/ittaiz/e4dd2efba31757fe4073) I've pasted the debug stack.

**Comment by jvanzyl** [comment]
It appears to be the line plugins in the DSL, I've commented them out and it appears to work now. The inline plugins need to be fixed but at least you can try it now.

**Comment by huntc** [comment]
I will also take a look today

**Comment by huntc** [comment]
https://github.com/takari/maven-polyglot/pull/22 resolves issues here.

**Comment by huntc** [comment]
I've also updated the example: https://github.com/takari/polyglot-maven-examples/pull/2

**Comment by jvanzyl** [comment]
Awesome, I'll merge this and do a release in the morning.

**Comment by jvanzyl** [comment]
Polyglot for Maven 0.1.7 release and the Scala example has been updated accordingly. Everything appears to be working now including inline Scala plugins.
